# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pseudonimo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'usuarios',
                'verbose_name': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Aparencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cores', models.CharField(max_length=128)),
                ('fonte', models.CharField(max_length=128)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'aparencia',
                'verbose_name': 'aparencia',
            },
        ),
        migrations.CreateModel(
            name='AprovacoesPoema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default='1999-11-11')),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('dataPublicacao', models.DateField(default='1999-11-11')),
                ('qtd_gostei', models.IntegerField(default=0)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'comentarios',
                'verbose_name': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('dataPublicacao', models.DateField(default='1999-11-11')),
                ('is_valid', models.BooleanField(default=0)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'denuncias',
                'verbose_name': 'denuncia',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('categoria', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('dataPublicacao', models.DateField(default='1999-11-11')),
                ('nome_autor', models.CharField(max_length=150)),
                ('arquivo', models.FileField(upload_to='')),
                ('avaliacao', models.IntegerField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'livros',
                'verbose_name': 'livro',
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default='1999-11-11')),
                ('aprovacao', models.BooleanField(default=False)),
                ('administrador', models.BooleanField(default=False)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poemese.Grupo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('conteudo', models.TextField()),
                ('dataPublicacao', models.DateField(default='1999-11-11')),
                ('qtd_gostei', models.IntegerField(default=0)),
                ('autor_poema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'poemas',
                'verbose_name': 'poema',
            },
        ),
        migrations.CreateModel(
            name='RelacoesAmizade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default='1999-11-11')),
                ('avaliacao', models.BooleanField(default=False)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny_relations', to=settings.AUTH_USER_MODEL)),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_relations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(through='poemese.ParticipacaoGrupo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_poema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poemese.Poema'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_poema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poemese.Poema'),
        ),
        migrations.AddField(
            model_name='aprovacoespoema',
            name='id_poema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poemese.Poema'),
        ),
    ]
