# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poemese', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprovacoesComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default='1999-11-11')),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poemese.Comentario')),
            ],
        ),
        migrations.RenameField(
            model_name='participacaogrupo',
            old_name='aprovacao',
            new_name='status_aprovacao',
        ),
        migrations.RenameField(
            model_name='relacoesamizade',
            old_name='avaliacao',
            new_name='status_aprovacao',
        ),
    ]
