# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemese', '0002_auto_20170420_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='livro',
            name='resumo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
