# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemese', '0006_remove_usuario_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images/'),
        ),
    ]
