# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemese', '0008_auto_20170501_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images/'),
        ),
    ]
