# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemese', '0009_auto_20170501_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile-images/'),
        ),
    ]
