# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poemese', '0010_auto_20170501_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='sugestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('dataPublicacao', models.DateField(default='1999-11-11')),
                ('valor_aprovacao', models.IntegerField(default=0)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_poema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poemese.Poema')),
            ],
        ),
    ]
