# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemese', '0011_sugestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='valor_aprovacao',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
