# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemese', '0013_livro_capa_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
