# Generated by Django 2.0.4 on 2018-10-21 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poemese', '0018_auto_20171130_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparencia',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aprovacoescomentario',
            name='aprovador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aprovacoescomentario',
            name='id_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poemese.Comentario'),
        ),
        migrations.AlterField(
            model_name='aprovacoespoema',
            name='aprovador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aprovacoespoema',
            name='id_poema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poemese.Poema'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_poema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poemese.Poema'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_poema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poemese.Poema'),
        ),
        migrations.AlterField(
            model_name='participacaogrupo',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poemese.Grupo'),
        ),
        migrations.AlterField(
            model_name='participacaogrupo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poema',
            name='autor_poema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relacoesamizade',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destiny_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relacoesamizade',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='origin_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sugestao',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sugestao',
            name='id_poema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poemese.Poema'),
        ),
    ]
